---
title: "exercise_01_sta426_staebler_jann"
author: "Jann Stäbler"
format: html
editor: visual
---

## Preliminaries

```{r}
# loading libraries
library(ggplot2) 
library(hrbrthemes)
library(dplyr)
```

## Part I: Sampling

Let's sample 100 values from a log-normal distribution

```{r}
a <- rlnorm(100, meanlog=5, sdlog=0.5) # a is our vector of the sample with mu=5 and sigma=0.5
```

## Part II: Plotting

Let's first plot the non-transformed histogram:

```{r}
df <- data.frame(value=a, A=c(rep("A")))  # creating a small data frame

# Histogram
ggplot(df, aes(x=value)) + 
     geom_histogram( binwidth=15, fill="#69b3a2", color="#e9ecef", alpha=0.9) +    ggtitle("Histogram of 100 samples of a log-normal distribution (mu=5, sigma=0.5)")  

# Violin plot
ggplot(df, aes(x=value, y=A)) + 
   ggtitle("Violinplot of the data displayed in the histogram above.")  +
geom_violin()
```

Now we plot the log-transformed values:

```{r}
ggplot(df, aes(x=log(a))) + 
     geom_histogram( binwidth=0.1, fill="#69b3a2", color="#e9ecef", alpha=0.9) +    ggtitle("Histogram of 100 samples of a log-normal distribution (log-transformed) (mu=5, sigma=0.5)")

# Violin plot
ggplot(df, aes(x=log(value), y=A)) + 
   ggtitle("Violinplot of the data displayed in the histogram above.")  +
geom_violin()
```

```{r}
mean_df <- round(mean(df$value)) #mean
sd_df <- round(sd(df$value)) #standard deviation
```

## Part III: Reporting results

The rounded mean of the sampled values is **`r mean_df`** and the rounded standard deviation is **`r sd_df`**.
